import type { Metadata } from 'next'
import Link from 'next/link'
import { notFound } from 'next/navigation'
import { POSTS, getPost, postSlugs, tocOf, relatedPosts, formatPostDate } from '@/lib/blog'
import { blockText } from '@/lib/blog/types'
import { getViewCounts } from '@/lib/blog/views-server'
import { BlockView } from '@/components/blog/Blocks'
import ArticleClient, { ArticleCta } from '@/components/blog/ArticleClient'
import { MoneyProvider, CurrencySwitcher } from '@/components/blog/Money'
import { getRates } from '@/lib/money/rates'
import { MONEY_RE, plainText } from '@/lib/blog/richtext'

const SITE = process.env.NEXT_PUBLIC_SITE_URL?.trim() || 'https://www.marrelay.com'

export const revalidate = 300

export function generateStaticParams() {
  return postSlugs().map((slug) => ({ slug }))
}

export function generateMetadata({ params }: { params: { slug: string } }): Metadata {
  const post = getPost(params.slug)
  if (!post) return { title: 'Article not found' }
  const url = `/blogs/${post.slug}`
  // The <title> may differ from the on-page H1: see Post.seoTitle.
  const seoTitle = post.seoTitle ?? post.title
  return {
    title: seoTitle,
    description: post.description,
    keywords: post.tags,
    alternates: { canonical: url },
    openGraph: {
      type: 'article',
      title: seoTitle,
      description: post.description,
      url,
      publishedTime: post.date,
      modifiedTime: post.updated ?? post.date,
      tags: post.tags,
      authors: [post.author.name],
      section: post.category,
    },
    twitter: { card: 'summary_large_image', title: seoTitle, description: post.description },
  }
}

export default async function ArticlePage({ params }: { params: { slug: string } }) {
  const post = getPost(params.slug)
  if (!post) notFound()

  const views = await getViewCounts()
  // Fetched server-side and cached for a day: see lib/money/rates.ts.
  const rates = await getRates()
  // Only articles that actually quote prices get a currency switcher.
  // MONEY_RE is a global regex, so .test() would advance lastIndex between
  // calls and skip matches. Search the serialised blocks once instead.
  const hasPrices = MONEY_RE.test(JSON.stringify(post.blocks))
  MONEY_RE.lastIndex = 0
  const related = relatedPosts(post.slug, 2, views)
  const toc = tocOf(post)

  const ld = {
    '@context': 'https://schema.org',
    '@type': 'BlogPosting',
    headline: post.title,
    description: post.description,
    // The per-article card generated by opengraph-image.tsx, not the shared
    // site header. Explicit dimensions let Google treat it as a usable image.
    image: [
      {
        '@type': 'ImageObject',
        url: `${SITE}/blogs/${post.slug}/opengraph-image`,
        width: 1200,
        height: 630,
      },
    ],
    datePublished: post.date,
    dateModified: post.updated ?? post.date,
    author: { '@type': 'Organization', name: 'Marrelay', url: SITE },
    publisher: {
      '@type': 'Organization',
      name: 'Marrelay',
      logo: { '@type': 'ImageObject', url: `${SITE}/assets/martek-mark.png` },
    },
    mainEntityOfPage: { '@type': 'WebPage', '@id': `${SITE}/blogs/${post.slug}` },
    articleSection: post.category,
    wordCount: post.blocks.map(blockText).join(' ').split(/\s+/).filter(Boolean).length,
    inLanguage: 'en',
    keywords: post.tags.join(', '),
  }

  // Breadcrumbs help Google show the Home > Blog > Article path in results.
  const crumbLd = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: 'Home', item: SITE },
      { '@type': 'ListItem', position: 2, name: 'Blog', item: `${SITE}/blogs` },
      { '@type': 'ListItem', position: 3, name: post.title, item: `${SITE}/blogs/${post.slug}` },
    ],
  }

  const faqBlock = post.blocks.find((b) => b.t === 'faq')
  const faqLd =
    faqBlock && faqBlock.t === 'faq'
      ? {
          '@context': 'https://schema.org',
          '@type': 'FAQPage',
          mainEntity: faqBlock.items.map((i) => ({
            '@type': 'Question',
            name: i.q,
            acceptedAnswer: { '@type': 'Answer', text: i.a },
          })),
        }
      : null

  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(ld) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(crumbLd) }} />
      {faqLd && <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqLd) }} />}

      <ArticleClient slug={post.slug} title={post.title} category={post.category} readMinutes={post.readMinutes} />

      <div className="wrap">
        <div className="crumb">
          <Link href="/">Home</Link>
          <span className="sep">/</span>
          <Link href="/blogs">Blog</Link>
          <span className="sep">/</span>
          <span className="here">{post.category}</span>
        </div>

        <header className="bp-head">
          <div className="bp-meta">
            <span className="bp-cat">{post.category}</span>
            <span>{formatPostDate(post.date)}</span>
            <span>·</span>
            <span>{post.readMinutes} min read</span>
          </div>
          <h1>{post.title}</h1>
          <p className="bp-excerpt">{plainText(post.excerpt)}</p>
          <div className="bp-author">
            <span className="bp-avatar" aria-hidden="true">M</span>
            <span>
              <b>{post.author.name}</b>
              <small>{post.author.role}</small>
            </span>
          </div>
        </header>

        <div className="bp-layout">
          <aside className="bp-toc" aria-label="On this page">
            <div className="bp-toc-inner">
              <b>On this page</b>
              <nav>
                {toc.map((h) => (
                  <a key={h.id} href={`#${h.id}`}>{h.text}</a>
                ))}
              </nav>
            </div>
          </aside>

          <article className="bp-article">
            <MoneyProvider rates={rates}>
              {hasPrices && <CurrencySwitcher />}
              {post.blocks.map((b, i) => <BlockView key={i} b={b} />)}
            </MoneyProvider>

            <div className="bp-tags">
              {post.tags.map((t) => <span key={t}>{t}</span>)}
            </div>

            <section className="bp-cta">
              <h3>Want this handled for you?</h3>
              <p>
                We are a founder-led studio in Toronto. If you would rather not do this yourself, we set it up properly,
                at a fixed price, and hand you everything.
              </p>
              <ArticleCta slug={post.slug} title={post.title} />
            </section>
          </article>
        </div>

        {related.length > 0 && (
          <section className="bp-related">
            <div className="kicker">Keep reading</div>
            <div className="bp-related-grid">
              {related.map((r) => (
                <Link key={r.slug} href={`/blogs/${r.slug}`} className="bp-card">
                  <span className="bp-card-cat">{r.category}</span>
                  <h3>{r.cardTitle ?? r.title}</h3>
                  <p>{plainText(r.excerpt)}</p>
                  <span className="bp-card-meta">{r.readMinutes} min read</span>
                </Link>
              ))}
            </div>
          </section>
        )}
      </div>
    </>
  )
}
